# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

compilers:
- compiler:
    spec: gcc@12.3.0
    paths:
      cc: /p/software/jusuf/stages/2024/software/GCCcore/12.3.0/bin/gcc
      cxx: /p/software/jusuf/stages/2024/software/GCCcore/12.3.0/bin/g++
      f77: /p/software/jusuf/stages/2024/software/GCCcore/12.3.0/bin/gfortran
      fc: /p/software/jusuf/stages/2024/software/GCCcore/12.3.0/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
